name: CI

on:
  push:
    branches:
      - "**" #double star includes a '/'.  single star doesnt match a '/'
    tags:
      - "**" #double star includes a '/'.  single star doesnt match a '/'
  schedule:
    # Daily at 05:44
    - cron: '44 5 * * *'

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.7.9

jobs:
  build:
    name: CI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Venv
        run: |
          #Install Poetry
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.path .
          poetry install

          poetry --version

      - name: python commands
        run: |
          set -vx
          poetry run pip --version
          poetry run black --check --diff .
          poetry run genbuildinfo "epyqlib/_build_generated.py"
          poetry run pip freeze --all
          poetry run builduiepyqlib
          poetry run pytest -vvvv -s --no-qt-log --run-factory epyqlib.tests --pyargs

          poetry run poetry-dynamic-versioning
          poetry build

      - name: Publish executable
        #only run if a new tag is created
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          poetry publish -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: epyq_st
          path: |
            dist/*
